# YouTube Downloader configuration
folder_video=C:\Users\Fjodr\Downloads\YouTube\Video
folder_music=C:\Users\Fjodr\Downloads\YouTube\Music
folder_channel=C:\Users\Fjodr\Downloads\YouTube\Channels
quality=best
container=mp4
audio=320
subs=none
thumb=yes
template=%(title)s.%(ext)s
cookies=none
client=default
